### PR TITLE
Fix capitalisation of Employee Type text in the read mode

### LINKED ISSUE #1481: The first letter of the employee type field should be capitalised in the read mode on organisation settings page
### Description

The first letter of the employee type field is not capitalised in the read mode on organization settings page

### Environment

    Linux / MacOS / Android / IOS / Windows
    Mozilla / Chrome / Safari

### What is the expected behaviour?

The first letter of the employee type field should be capitalised in the read mode on organization settings page

### What is the current behaviour?

The first letter of the employee type field is not capitliazed in the read mode on organization settings page

### How to reproduce the issue?

1. Login as any user 
2. Click on settings from the left navigation menu
3. Click on organization settings 
4. Click on edit button 

### Screenshots or Screencast

Edit mode - Screenshot 2023-09-25 at 1 07 02 PM

Read mode - 
Screenshot 2023-09-25 at 1 04 41 PM

### Please provide any traces or logs that could help here.

NA

### Any possible solutions?

NA

### PR DESCRIPTION
**Pull request by ameen4455**
Fixes #1481 

We receive an uncapitalised employee type string from the API. The edit screen uses the `employeeTypes`'s `label` and the `value` attribute is saved to the server. So this PR implements a mapper for `employeeTypes`

Screenshot 2023-09-28 at 11 11 12 AM

### CODE REVIEW

**Comment by supriya3105** [comment]
@Shruti-Apte Please review and approve if no changes are required.

File: app/javascript/src/components/Profile/UserDetail/EmploymentDetails/helpers.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+export const employeeTypes = [
+  { label: "Salaried Employee", value: "salaried" },
+  { label: "Contractor", value: "contractor" },
+];
+
+export function getLabelForValue(valueToFind: string): string | null {
```
Comment (Shruti-Apte) [inline app/javascript/src/components/Profile/UserDetail/EmploymentDetails/helpers.ts:6]: Can you rename the function to` getLabelForEmployeeType` or something similar? The current name is confusing.

Comment (ameen4455) [reply app/javascript/src/components/Profile/UserDetail/EmploymentDetails/helpers.ts]: Sure, I updated the name

**Review by Shruti-Apte — APPROVED** [review]
