### PR TITLE
Disable pay button if amount less than 0

### LINKED ISSUE #1734: Disable pay button if amount to be paid is 0
Current behavior:
If an invoice is created with amount 0, for a client login, I can see an invoice for amount 0 and the pay button is enabled.
If the user clicks to pay, an error message is displayed.

Image

Expected behavior:
The pay button should be disabled if the amount is 0 or negative.

Steps to reproduce:
- From admin, send an invoice to client for amount $
- From the client login, go to the invoices tab, select an invoice to pay, and click on the "Pay" button.
- above error screen is displayed

### PR DESCRIPTION
**Pull request by apoorv1316**
Closes #1734 

- Disable pay button if amount <=0
- Remove year from copyright

### CODE REVIEW

**Comment by apoorv1316** [comment]
@nisusam Please review

File: app/javascript/src/components/ClientInvoices/Details/Header.tsx [hunk 1]
```diff
@@ -71,13 +71,15 @@ const Header = ({
             </Tooltip>
           ) : (
             <button
-              disabled={status == "paid"}
               className={`flex h-10 w-44 flex-row items-center justify-center rounded
               ${
-                status == "paid"
+                status == "paid" || status == "waived" || invoice.amount <= 0
```
Comment (nisusam) [inline app/javascript/src/components/ClientInvoices/Details/Header.tsx:76]: Save it in variable & reuse the same

**Review by nisusam — APPROVED** [review]
Fix & Ship!
