### PR TITLE
Fixed documentation and add employee user to seed data

### LINKED ISSUE #995: Fix documentation and add employee user to seed data
What:

- I merged https://github.com/saeloun/miru-web/pull/992 to make it so that data is always relative to US clients
- Add a new "Employee" user- "Sam Smith", "sam@example.com"
- The documentation needs to be updated for this user and related password

### PR DESCRIPTION
**Pull request by prasanthchaduvula**
Closes #995 
## Summary

- Added a new "Employee" user- "Sam Smith", "[sam@example.com](mailto:sam@example.com)"
- Updated documentation for the users and related passwords

### CODE REVIEW

File: db/seeds.rb [hunk 1]
```diff
@@ -54,7 +58,7 @@
 
 puts "Projects Created"
 
-[supriya, vipul, book_keeper].each do |user|
+[supriya, vipul, book_keeper, sam].each do |user|
```
Comment (vipulnsward) [inline db/seeds.rb:61]:
```suggestion
users.each do |user|
```

**Review by vipulnsward — APPROVED** [review]
