### PR TITLE
Fixed issues in invoice preview

### LINKED ISSUE #1814: Fix responsiveness of invoice email preview
Steps to reproduce
1. Send invoice to client
2. Click on view invoice on the email received
3. Open the redirected invoice on mobile screen

Screenshot 2024-04-19 at 12 40 09 PM

Screenshot 2024-11-12 at 11 31 07 AM

Screenshot 2024-11-12 at 11 31 00 AM

If the invoice is Deleted and we try to open that invoice from the email we are getting stuck:

Screenshot 2024-11-12 at 11 31 49 AM

### PR DESCRIPTION
**Pull request by Shruti-Apte**
Closes #1814 

### What:
- Fixed fonts on extra small mobile screens
- Handled No invoice found loading error.

### CODE REVIEW

File: app/javascript/src/components/InvoiceEmail/index.tsx [hunk 1]
```diff
@@ -32,10 +33,14 @@ const InvoiceEmail = () => {
...
-    setData(res.data);
-    setIsStripeConnected(res.data.stripe_connected_account);
-    setLoading(false);
+    try {
+      const res = await invoicesApi.viewInvoice(params.id);
+      setData(res.data);
+      setIsStripeConnected(res.data.stripe_connected_account);
+      setLoading(false);
+    } catch {
+      navigate("/");
```
Comment (gowsik-ragunath) [inline app/javascript/src/components/InvoiceEmail/index.tsx:42]: Can we display an error toast with the message "Invoice not found"?

**Review by gowsik-ragunath — APPROVED** [review]
LGTM, left a minor comment.

File: app/javascript/src/components/InvoiceEmail/index.tsx (hunk 1 above)
Comment (gowsik-ragunath) [reply app/javascript/src/components/InvoiceEmail/index.tsx:42]: @Shruti-Apte Okay then, please merge this PR.
