### PR TITLE
fix: gracefully handle Postmark inactive recipient errors

### LINKED ISSUE #2050: Postmark::InactiveRecipientError occurring when sending weekly reminder emails to users whose email addresses have been marked as inactive by Postmark
### Description

Postmark::InactiveRecipientError occurring when sending weekly reminder emails to users whose email addresses have been marked as inactive by Postmark. This happens when users are removed from the organization but their accounts remain active in Miru, causing 167+ error occurrences since November 2024.

**Sentry Issue Reference:** https://saeloun-inc.sentry.io/issues/MIRU-WEB-2H

### Environment

- **OS**: Linux (Production server on Fly.io)
- **Ruby**: 3.3.10
- **Rails**: 7.1.5.2
- **Email Provider**: Postmark
- **Environment**: Production

### What is the expected behaviour?

When sending emails to inactive recipients (hard bounces, spam complaints, or manually suppressed addresses), the system should:
1. Gracefully handle the error without raising exceptions
2. Log the failed delivery attempt
3. Automatically add the email to a suppression list
4. Skip future email attempts to that address

### What is the current behaviour?

1. Weekly reminder job attempts to send email to inactive recipient (e.g., my_username@emailprovider.com)
2. Postmark rejects the email with `InactiveRecipientError`
3. Exception is raised and logged to Sentry
4. Job fails but will retry next week with the same result
5. No automatic suppression - same error repeats indefinitely

### How to reproduce the issue?

1. Have a user account in Miru with an email that's been marked inactive in Postmark
2. Wait for the weekly reminder job to run (or trigger manually)
3. Job attempts to send email via `SendWeeklyReminderToUserMailer.notify_user_about_missed_entries`
4. Postmark returns error: "You tried to send to recipient(s) that have been marked as inactive"
5. Exception is raised and logged to Sentry

### Screenshots or Screencast

N/A - Error details available in Sentry

### Please provide any traces or logs that could help here.

**Error Message:**
```
Postmark::InactiveRecipientError: You tried to send to recipient(s) that have been marked as inactive.
Found inactive addresses: my_username@emailprovider.com.
Inactive recipients are ones that have generated a hard bounce, a spam complaint, or a manual suppression.
```

**Job Details:**
```ruby
Job: ActionMailer::MailDeliveryJob
Mailer: SendWeeklyReminderToUserMailer
Action: notify_user_about_missed_entries
Recipient: my_username@emailprovider.com
Company: Email Provider Inc
User: My Username
```

**Stack Trace (Key Frames):**
```
from postmark (1.25.1) lib/postmark/http_client.rb:78:in `handle_response`
from actionmailer (7.1.5.2) lib/action_mailer/mail_delivery_job.rb:28:in `perform`
```

### Any possible solutions?

**Solution: Add error handling in ApplicationMailer** (Implemented)

Add `rescue_from` handlers to gracefully catch Postmark errors and automatically suppress bounced emails:

```ruby
class ApplicationMailer < ActionMailer::Base
  rescue_from Postmark::InactiveRecipientError do |exception|
    handle_inactive_recipient(exception)
  end

  rescue_from Postmark::InvalidEmailError do |exception|
    handle_invalid_email(exception)
  end

  private

  def handle_inactive_recipient(exception)
    # Extract email addresses from error message
    inactive_emails = exception.message.scan(/[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+/i)

    Rails.logger.warn("Email delivery failed - Inactive recipient(s): #{inactive_emails.join(', ')}")

    # Store in database to prevent future attempts
    inactive_emails.each do |email|
      SesInvalidEmail.find_or_create_by(email: email.downcase)
    end
  end
end
```

**Why this works:**
- The service already checks `SesInvalidEmail` before sending (line 3 in `weekly_reminder_for_missed_entries_service.rb`)
- Once an email is added to this table, it's automatically skipped in future runs
- Self-healing: first failure adds to suppression list, preventing future errors
- Works for all mailers since they inherit from ApplicationMailer

**Alternative solutions considered:**
1. ❌ Manual database cleanup - requires ongoing maintenance
2. ❌ Query Postmark suppression list before sending - adds API overhead
3. ❌ Add separate bounced_email flag to users - duplicates existing SesInvalidEmail functionality

### If the bug is confirmed, would you be willing to submit a PR?

Yes, PR is ready with the fix implemented in `app/mailers/application_mailer.rb`.

### PR DESCRIPTION
**Pull request by amolmjoshi93**
Closes #2050 

- Add rescue_from handlers in ApplicationMailer for Postmark errors
- Automatically store inactive/invalid emails in SesInvalidEmail table
- Log warnings instead of raising exceptions for bounced emails
- Prevents 167+ recurring errors when sending to inactive recipients

When users are removed from the organization but their accounts remain active in Miru, weekly reminder emails would fail with Postmark::InactiveRecipientError. This caused job failures and Sentry alerts without any way to recover.

Changes:
- app/mailers/application_mailer.rb: Add rescue_from for InactiveRecipientError and InvalidEmailError, automatically adding bounced emails to suppression list

The service already checks SesInvalidEmail before sending, so once an email is added to this table, future attempts will be skipped automatically.

Benefits:
- No more Sentry errors for inactive recipients
- Self-healing: bounced emails are automatically suppressed
- Works for all mailers (inherits from ApplicationMailer)
- Maintains existing SesInvalidEmail checking logic

Sentry Issue: https://saeloun-inc.sentry.io/issues/MIRU-WEB-2H

## Summary by CodeRabbit

* **Bug Fixes**
  * Added handling for inactive/invalid email recipients from the delivery service; occurrences are logged and invalid addresses are persisted to prevent repeat delivery attempts and improve reliability. New informational logging notes when an invalid address is newly recorded.

* **Tests**
  * Added specs validating email-address extraction (single, multiple, subdomains, special chars) and confirming the mailer’s inactive-recipient error handling.

### CODE REVIEW

File: app/mailers/application_mailer.rb [hunk 1]
```diff
@@ -4,4 +4,26 @@ class ApplicationMailer < ActionMailer::Base
...
+      # Use non-capturing group (?:...) to get full email addresses
+      inactive_emails = exception.message.scan(/[\w+\-.]+@[a-z\d-]+(?:\.[a-z\d-]+)*\.[a-z]+/i)
+
+      Rails.logger.warn("Email delivery failed - Inactive recipient(s): #{inactive_emails.join(', ')}")
+      Rails.logger.warn("Error details: #{exception.message}")
+
+      # Store inactive emails in the database to prevent future attempts
+      inactive_emails.each do |email|
+        email_downcase = email.downcase
+        record = SesInvalidEmail.find_or_create_by(email: email_downcase)
```
[the remark this answers is not in the document]
Comment (amolmjoshi93) [reply app/mailers/application_mailer.rb]: Done

File: Gemfile [hunk 2]
```diff
@@ -139,6 +139,10 @@ gem "ahoy_matey"
 
 gem "httparty", ">= 0.24.0"
 
+# Security updates
```
Comment (vipulnsward) [inline Gemfile]: Please remove these and upgrade directly

File: app/mailers/application_mailer.rb [hunk 3]
```diff
@@ -4,4 +4,27 @@ class ApplicationMailer < ActionMailer::Base
   append_view_path Rails.root.join("app", "views", "mailers")
   default from: ENV["DEFAULT_MAILER_SENDER"]
   layout "mailer"
+
+  # Email regex based on URI::MailTo::EMAIL_REGEXP but without anchors for scanning
+  EMAIL_SCAN_REGEXP = /[a-zA-Z0-9.!\#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*/
```
Comment (vipulnsward) [inline app/mailers/application_mailer.rb]: Never add such constants, always use library
