### PR TITLE
Fix: use badge components across the app

### LINKED ISSUE #708: Use Badge components across the app
### Present:
Recently we created `Badge` reusable StyledComponent. Instead of custom code & styling we have to reuse it across the frontend. Wherever we have these below styling like projects, invoices, clients in all component view we have below Badges. In all these components we written custom styling. Lets use the `Badge ` component in the code base. Wherever there is `getStatusCssClass` mostly the styling is related to `Badge` type style. 

Screenshot 2022-10-06 at 10 08 27 AM

### Solution

**Default style**
Screenshot 2022-10-06 at 10 16 55 AM
```
import { Badge } from "StyledComponents"

<Badge />
```

**Updating Props to customise the style**
Screenshot 2022-10-06 at 10 20 36 AM

Where ever we need `Badge` component. use `className` to override the default styles. For color codes,  please check `tailwind.config.js` file. 

```
import { Badge } from "StyledComponents"

<Badge
     text="non billable"
     color="text-miru-dark-purple-600"
      bgColor="bg-miru-dark-purple-100"
      className="uppercase"
  />
```

### PR DESCRIPTION
**Pull request by mayankagnihotri7**
Fixes #708 
## Summary

- Used badge components across the app, wherever it was not being used.

## Preview

https://user-images.githubusercontent.com/57438322/196899416-c16c66dd-0555-4fda-a8aa-d0064e3a24cc.mp4

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

### CODE REVIEW

File: app/javascript/src/components/Projects/Details/index.tsx [hunk 1]
```diff
@@ -175,9 +176,10 @@ const ProjectDetails = () => {
               {project?.name}
             </h2>
             {project?.is_billable && (
-              <span className="rounded-xl text-xs self-center  tracking-widest font-semibold px-1 bg-miru-han-purple-100 text-miru-han-purple-1000">
-                BILLABLE
-              </span>
+              <Badge text="BILLABLE"
```
Comment (prasanthchaduvula) [inline app/javascript/src/components/Projects/Details/index.tsx:179]: @mayankagnihotri7 Instead of writing `text="BILLABLE"` make it into smallcase `text="billable"` and add `uppercase` to className

You can also use `getStatusCssClass`
Below is an example
```
import { Badge } from "StyledComponents";
import getStatusCssClass from "utils/getBadgeStatus";
<Badge
          text={invoice.status}
          className={`${getStatusCssClass(invoice.status)} uppercase`}
        />
```

File: app/javascript/src/components/Projects/List/project.tsx [hunk 2]
```diff
@@ -51,7 +52,12 @@ export const Project = ({
         </p>
       </td>
       <td className="table__cell text-right">
-        {isBillable && <span className="px-1 tracking-widest rounded-lg text-xs font-semibold leading-4 bg-miru-han-purple-100 text-miru-han-purple-1000">Billable</span>}
+        {isBillable &&(
+          <Badge text="Billable"
```
Comment (prasanthchaduvula) [inline app/javascript/src/components/Projects/List/project.tsx:56]: @mayankagnihotri7 Instead of writing `text="Billable"` make it into smallcase `text="billable"` and add `capitalize` to className. Also verify whether we need to be full uppercase or not.

You can also use `getStatusCssClass`
Below is example
```
import { Badge } from "StyledComponents";
import getStatusCssClass from "utils/getBadgeStatus";
<Badge
          text={invoice.status}
          className={`${getStatusCssClass(invoice.status)} uppercase`}
        />
```

**Review by prasanthchaduvula — CHANGES_REQUESTED** [review]

**Review by apoorv1316 — APPROVED** [review]

**Comment by mayankagnihotri7** [comment]
@prasanthchaduvula I've made the requested changes. Please review.

**Review by prasanthchaduvula — APPROVED** [review]
